server:
  port: 8080

spring:
  profiles:
    active: local  # Change this for different environments
---
spring:
  config:
    activate:
      secret: a-string-secret-at-least-256-bits-long
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/mvpcloudseal
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  jpa:
    hibernate:
      ddl-auto: update


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  jpa:
    hibernate:
      ddl-auto: update



