server:
  port: 8080

spring:
  profiles:
    active: local  # Change this for different environments
---
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    activate:
      secret: a-string-secret-at-least-256-bits-long
      on-profile: local
  datasource:
    url: jdbc:mysql://google/MVPCLOUDSEALS?
         cloudSqlInstance=observability-459214:us-central1:cseals-mysqldb
         &socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: gopi
    password: Gmail@123
  jpa:
    hibernate:
      ddl-auto: none


---
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  jpa:
    hibernate:
      ddl-auto: none


---
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  jpa:
    hibernate:
      ddl-auto: none



